### ISSUE TITLE
how can i change the size of the logo?

### ISSUE THREAD

**Issue by Jimmi08** [Jimmi08/e107themeLegit#2]
i want the logo to be bigger, the way its now... while in mobile devices the padding is not right for the logo

**Comment by Jimmi08** [comment]
related:
http://e107help.org/1846/sitelogo-height?show=1846#q1846

**Comment by Jimmi08** [comment]
in theme_shortcodes.php  find this function and change 30 to your value
![image](https://cloud.githubusercontent.com/assets/5429548/14979885/7501b628-1125-11e6-9b3b-d94b769a6fe7.png)

you know that it's e107 related (and not css issue) because this:
![image](https://cloud.githubusercontent.com/assets/5429548/14979927/c29d5036-1125-11e6-8dcf-9a9393642210.png)

you test in inspector to see result before changing theme code
![image](https://cloud.githubusercontent.com/assets/5429548/14979960/fd9bf52a-1125-11e6-8cf2-1cf42d8bafe7.png)

Then you change code and correct padding etc (css styling), for example:
![image](https://cloud.githubusercontent.com/assets/5429548/14980030/583d5a78-1126-11e6-8569-19502d7865da.png)
![image](https://cloud.githubusercontent.com/assets/5429548/14980044/7409bc60-1126-11e6-9dd6-947fa1299a33.png)

result with 100px
![image](https://cloud.githubusercontent.com/assets/5429548/14980055/82a933b8-1126-11e6-8058-104e5e2240d9.png)

**Comment by Cr0ssix** [comment]
what padding did you use in the last screenshot?

**Comment by Jimmi08** [comment]
zero, with deleted line if felt back to default.

**Comment by Cr0ssix** [comment]
ok how can i deleted the red vertical lines between menus ? thanks

**Comment by Jimmi08** [comment]
Do you mean this?
https://github.com/Jimmi08/e107themeLegit/issues/1

**Comment by Cr0ssix** [comment]
yes. thank you Jana

**Comment by Jimmi08** [comment]
just create new issue with new question, the best with picture and I will try answer while you are sleeping :)  Now I need to go to bed.

**Comment by Jimmi08** [comment]
![image](https://cloud.githubusercontent.com/assets/5429548/15161866/2c23fb42-1700-11e6-91e0-fa172707180b.png)
